Move load_nodes() out of Vagrant.configure
Having it within seems to cause it to be called twice which is evidenced by
two error messages when you have an old `nodes.local.json` file:

➜  vagrant-govuk git:(69925732-vcloud_launcher_yaml) ✗ vagrant status
ERROR: nodes.local.json is deprecated. Please convert it to YAML
ERROR: nodes.local.json is deprecated. Please convert it to YAML